### PR TITLE
Parallel OutputBus trait

### LINKED ISSUE #18: Parallel GPIO 8-bit interface does not work if the data bus pins are not zero on init
When a new interface is created with `PGPIO8BitInterface::new()` the function assumes that all the pins are set to low beforehand. If that's not the case, the driver will start in an unexpected state because `last` is set to 0.

We should either drive the entire bus low on `new()`, or at least add this to the documentation. I would personally incline towards driving the pins low on initialization to ensure that the driver will work correctly even if the user fails to read one sentence in the documentation.

### PR DESCRIPTION
**Pull request by GrantM11235**
## OutputBus
This PR changes `PGPIO8BitInterface` to use a simple `OutputBus` trait instead of a bunch of individual pins:
```rust
pub trait OutputBus {
    type Word: Copy;

    fn set_value(&mut self, value: Self::Word) -> Result<(), DisplayError>;
}
```

## Generic8BitBus
This PR also provides an `OutputBus` implementation that can be constructed from 8 `OutputPin`s:
```Rust
let bus = Generic8BitBus::new((p0, p1, p2, p3, p4, p5, p6, p7)).unwrap()
```
or 
```Rust
let bus = (p0, p1, p2, p3, p4, p5, p6, p7).try_into().unwrap()
```
(Note that the construction is fallible because it attempts to set all the pins low, which fixes #18)

## Custom OutputBus
For reference, here is an example of an optimized `OutputBus` implementation for an stm32f1 with a bus on pins PB0 through PB7
```rust
pub struct OutputBusPins(
    PB0<Output<PushPull>>,
    PB1<Output<PushPull>>,
    PB2<Output<PushPull>>,
    PB3<Output<PushPull>>,
    PB4<Output<PushPull>>,
    PB5<Output<PushPull>>,
    PB6<Output<PushPull>>,
    PB7<Output<PushPull>>,
);

impl OutputBus for OutputBusPins {
    type Word = u8;

    fn set_value(&mut self, value: Self::Word) -> Result<(), DisplayError> {
        let bits = 0x00ff_0000 | value as u32;

        unsafe { (*hal::pac::GPIOB::ptr()).bsrr.write(|w| w.bits(bits)) }

        Ok(())
    }
}
```

## Pros
- `PGPIO8BitInterface` doesn't take a million arguments anymore
- Users can create their own non-HAL implementations of `OutputBus` with much higher performance
- When combined with #19, this allows us to trivially add support for 16 bit buses
- Still works with heterogeneous pin types
- Fixes #18

## Cons
- Users must construct an `OutputBus` before they can construct a `PGPIO8BitInterface`. This is slightly more verbose, but it is more readable in my opinion

## Todo
- [x] Add/update documentation
- [x] Update changelog

### CODE REVIEW

**Comment by therealprof** [comment]
That's a good improvement, I like it. 

Nit: Your example impl of `set_value` doesn't match the trait definition.

NB: I have been meaning to add support for parallel busses to `embedded-hal` but never got to it. Maybe it's time to revive this idea?

**Comment by andresovela** [comment]
Looks like a great alternative to me, but I'll have to say that this still doesn't fully fix #18, because the user can still implement a custom `OutputBus` that doesn't drive all pins low when instantiated

File: parallel-gpio/src/lib.rs [hunk 1]
```diff
@@ -6,6 +6,98 @@ use embedded_hal::digital::v2::OutputPin;
...
+        where
+            $($PX: OutputPin, )*
+        {
+            pub fn new(pins: ($($PX, )*)) -> Result<Self, DisplayError> {
+                let mut bus = Self { pins, last: $Word::MAX };
+
+                bus.set_value(0)?;
+
+                Ok(bus)
+            }
```
Comment (andresovela) [inline parallel-gpio/src/lib.rs:32]:
```suggestion
            pub fn new(pins: ($($PX, )*)) -> Self {
                Self { pins, last: $Word::MAX }
            }
```

File: parallel-gpio/src/lib.rs [hunk 2]
```diff
@@ -18,170 +110,37 @@ pub use display_interface::{DataFormat, DisplayError, WriteOnlyDataCommand};
...
-            p5,
-            p6,
-            p7,
-            dc,
-            wr,
-            last: 0,
-        }
+    pub fn new(bus: BUS, dc: DC, wr: WR) -> Self {
+        Self { bus, dc, wr }
     }
```
Comment (andresovela) [inline parallel-gpio/src/lib.rs:128]:
```suggestion
    pub fn new(bus: BUS, dc: DC, wr: WR) -> Result<Self, DisplayError> {
        bus.set_value(0)?;
        Ok(Self { bus, dc, wr })
    }
```

**Review by andresovela — CHANGES_REQUESTED** [review]
I think with these changes this would fix #18

**Comment by GrantM11235** [comment]
@therealprof 
> That's a good improvement, I like it.

Thanks!

> Nit: Your example impl of `set_value` doesn't match the trait definition.

Oops, fixed

> NB: I have been meaning to add support for parallel busses to `embedded-hal` but never got to it. Maybe it's time to revive this idea?

An `embedded-hal` trait would be great! I saw that there is a `digital::OutputPort` RFC, I plan to add some of my thoughts there.

---

@andresovela 
> Looks like a great alternative to me

Thanks!

> but I'll have to say that this still doesn't fully fix #18, because the user can still implement a custom OutputBus that doesn't drive all pins low when instantiated

The `OutputBus` trait doesn't require the bus to have any specific value until the first time that `set_value` is called. #18 is fixed for `Generic8BitBus` by synchronizing the state of the pins with the value of `self.last`, it does this by setting `self.last` to all ones before calling `self.set_value(0)` which forces all pins to zero regardless of their previous state.

An implementation of `OutputBus` that unconditionally sets all pins, like my example, will never exhibit the symptoms of #18

I will be sure to make a note of all of this when I write the docs.

File: parallel-gpio/src/lib.rs (hunk 1 above)
Comment (GrantM11235) [reply parallel-gpio/src/lib.rs:32]: This is unsound because
```rust
let bus = Generic8BitBus::new(pins);
bus.set_value(0xff)?;
```
would just leave all the pins in their initial state

Comment (andresovela) [reply parallel-gpio/src/lib.rs:32]: I don't understand. Unsound how? There's no unsafe code anywhere AFAICT

**Comment by andresovela** [comment]
> The OutputBus trait doesn't require the bus to have any specific value until the first time that set_value is called. #18 is fixed for Generic8BitBus by synchronizing the state of the pins with the value of self.last, it does this by setting self.last to all ones before calling self.set_value(0) which forces all pins to zero regardless of their previous state.

Yeah I know, I'm not arguing that `Generic8BitBus` has the problem described in #18.

> An implementation of OutputBus that unconditionally sets all pins, like my example, will never exhibit the symptoms of #18

This is already the case. A user implementing a `PGPIO8BitInterface` that unconditionally sets all pins to 0 in the beginning will never see #18.

Anyway, now that I think about it, with your implementation this is a non-issue, because if such a problem comes up it will be the user's fault and not this crate's fault, since the user has the responsibility of implementing this correctly.

File: parallel-gpio/src/lib.rs (hunk 1 above)
Comment (GrantM11235) [reply parallel-gpio/src/lib.rs:32]: I just mean that calling `bus.set_value(0xff)` will return `Ok(())` without actually changing the state of the pins. If the pins are low before the `Generic8BitBus` is created, they will still be low after `bus.set_value(0xff)`

**Comment by GrantM11235** [comment]
> Anyway, now that I think about it, with your implementation this is a non-issue, because if such a problem comes up it will be the user's fault and not this crate's fault, since the user has the responsibility of implementing this correctly.

Exactly :wink:

**Comment by therealprof** [comment]
I think this is a great PR. Is this ready to be merged?

**Comment by GrantM11235** [comment]
It is now! :+1: 

Let me know if I should squash anything.

**Comment by therealprof** [comment]
A squash would be nice, yes.

**Review by therealprof — APPROVED** [review]
LGTM, thanks for sticking with me.
